// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebCrf;

namespace WebCrf.Migrations
{
    [DbContext(typeof(CrfDbContext))]
    [Migration("20181121074921_initial_Create")]
    partial class initial_Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebCrf.Models.tb_role", b =>
                {
                    b.Property<int>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Deskripsi");

                    b.Property<string>("NamaRole");

                    b.HasKey("IdRole");

                    b.ToTable("tb_roles");
                });

            modelBuilder.Entity("WebCrf.Models.tb_user", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat");

                    b.Property<string>("Email");

                    b.Property<string>("Gambar");

                    b.Property<string>("JenisKelamin");

                    b.Property<string>("NamaUser");

                    b.Property<string>("Sandi");

                    b.HasKey("IdUser");

                    b.ToTable("tb_users");
                });

            modelBuilder.Entity("WebCrf.Models.tb_user_role", b =>
                {
                    b.Property<int>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Tb_UserIdUser");

                    b.Property<int?>("tb_roleIdRole");

                    b.HasKey("IdUserRole");

                    b.HasIndex("Tb_UserIdUser");

                    b.HasIndex("tb_roleIdRole");

                    b.ToTable("tb_user_roles");
                });

            modelBuilder.Entity("WebCrf.Models.tb_user_role", b =>
                {
                    b.HasOne("WebCrf.Models.tb_user", "Tb_User")
                        .WithMany()
                        .HasForeignKey("Tb_UserIdUser");

                    b.HasOne("WebCrf.Models.tb_role", "tb_role")
                        .WithMany()
                        .HasForeignKey("tb_roleIdRole");
                });
#pragma warning restore 612, 618
        }
    }
}
